---

####################
# Create the S3 bucket for the Kops state store
####################

# Create a simple s3 bucket
- name: Delete S3 bucket
  ignore_errors: yes
  s3_bucket:
        name: "{{ state_store | replace('s3://', '') }}"
        state: absent
        region: "{{ aws_region }}"
        versioning: no
        tags:
            Name: "{{ state_store | replace('s3://', '') }}"
            Owner: "{{ tag_owner }}"
            Application: "{{ tag_application }}"
            CostCenter: "{{ tag_costcenter }}"
            Environment: "{{ tag_environment }}"