- hosts: localhost
  gather_facts: true
  roles:
   - role: networking
   - role: state_store
   #- role: create_cluster
   - role: deployment
   - role: ingress_and_prometheus
   - role: benchmark
   - role: generate_report
