
- name: Install Nginx 
  ansible.builtin.command: helm upgrade --install "{{ ingress_chart_name }}" ingress-nginx \
                           --repo https://kubernetes.github.io/ingress-nginx \
                           --namespace "{{ ingress_namespace  }}" --create-namespace

- name: Install Prometheus
  ansible.builtin.command: helm upgrade --install "{{ prometheus_chart_name }}" kube-prometheus-stack \
                           --repo https://prometheus-community.github.io/helm-charts \
                           --namespace "{{ prometheus_namespace }}" --create-namespace

- name: Update Ingress Metric Collection
  ansible.builtin.command: helm upgrade --install "{{ ingress_chart_name }}" ingress-nginx --repo https://kubernetes.github.io/ingress-nginx \
                        --namespace "{{ ingress_namespace  }}" --create-namespace \
                        --set controller.metrics.enabled=true \
                        --set controller.metrics.serviceMonitor.enabled=true \
                        --set controller.metrics.serviceMonitor.additionalLabels.release="{{ prometheus_chart_name }}"
                         
- name: Update Prometheus Service Access
  ansible.builtin.command: helm upgrade --install "{{ prometheus_chart_name }}" kube-prometheus-stack --repo 'https://prometheus-community.github.io/helm-charts' \
                            --namespace "{{ prometheus_namespace  }}"  --create-namespace \
                            --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false \
                            --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false

- name: Estabilish Tunnel
  shell: "nohup kubectl port-forward svc/prometheus-kube-prometheus-prometheus -n prometheus 9000:9090 </dev/null >/dev/null 2>&1 &"
                          
