---
cluster_name: kubernetes-lb-digi.alphagroup-aws.io
state_store: s3://kops-state-store-beta

## Remote access
ssh_public_key: ~/.ssh/id_rsa.pub


## Regions / Availability zones
aws_region: us-east-1
aws_zones: us-east-1a,us-east-1b
master_zones: us-east-1a


## Network
dns_zone: alphagroup-aws.io
vpc_name: alphagroup
network_cidr: 172.16.0.0/16
subnet_cidr: 172.16.1.0/24
subnet_name: public_subnet
route_name: public_route
igw_name: alphagroup-igw

kubernetes_networking: calico

# Topology must be either public or private
topology: public


## EC2 host sizing
base_image: ubuntu/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200423

# Master configuration
master_size:  t2.medium #m4.xlarge
master_count: 1
master_volume_size: 50

# Node configuration
node_size: t2.medium #m4.xlarge
node_count: 1
node_volume_size: 50

node_autoscaler_min: 1
node_autoscaler_max: 6


## Tags
tag_owner: alphagroup
tag_application: Demo
tag_costcenter: 8877669
tag_product: payment_gateway
tag_environment: Dev


## Cluster spec
kubernetes_version: 1.20.15

# Kops
kops_version: "v1.22.3"

#Ingress & Prometheus
ingress_namespace: "ingress-controller"
ingress_chart_name: "controller"
prometheus_namespace: "prometheus"
prometheus_chart_name: "prometheus"

chart_url: "https://charts.helm.sh/stable"
