---    
# Render templates

- name: POD Deployment
  template:
    src: deployment.yaml.j2
    dest: /tmp/deployment.yaml
    mode: 0644
  become: false

- name: Deploy Foo & Bar Pod
  command: "kubectl apply -f /tmp/deployment.yaml"
