---

  #############
  # Install Kubectl
  #############
  
  - name: Download Kubectl binaries
    get_url:
      url: "{{ kubectl_xos_download_path }}/{{ item }}"
      dest: /tmp #/usr/local/bin
      owner: root
      group: admin
      mode: 0755
      force: yes
    with_items:
      - kubectl
    when: ansible_os_family == 'Darwin'
    become: true
  
  - name: Download Kubectl binaries
    get_url:
      url: "{{ kubectl_download_path }}/{{ item }}"
      dest: /usr/local/bin
      owner: root
      group: root
      mode: 0755
      force: yes
    with_items:
      - kubectl
    when: ansible_os_family != 'Darwin'
    become: true