---
# tasks file for kops
- name: Install AWS Collection
  shell: "ansible-galaxy collection install community.aws"

- name: Install Python dependency
  pip:
    name: "{{ packages }}"
  vars:
    packages:
    - boto3
    - requests

- name: Download Kops binaries
  get_url:
    url: "{{ kops_darwin_download_path }}"
    dest: /usr/local/bin/kops
    owner: root
    group: admin
    mode: 0755
    force: yes
  when: ansible_os_family == 'Darwin'
  become: true

- name: Download Kops binaries
  get_url:
    url: "{{ kops_download_path }}"
    dest: /usr/local/bin/kops
    owner: root
    group: root
    mode: 0755
    force: yes
  when: ansible_os_family != 'Darwin'
  become: true

- include: kubectl.yaml